### ISSUE TITLE
Zu viele IP-Adressen in der Blockierungsliste

### ISSUE THREAD

**Issue by restaurierung** [geimist/Update_Blocklist#1]
Hallo

Zuerst vielen Dank für das Blocklist Script. Ich setze es seit langem ein und lasse auch immer die updates aufspielen.
Nun erhalte ich aber die Meldung, dass "Zu viele IP-Adressen in der Blockierungsliste" seien.
Kann ich im Script einstellen, dass nach einer bestimmten Anzahl blockierter LPs in der Liste, die ältesten Einträge automatisch entfernt werden?

Besten Dank und Gruss aus der Schweiz
Andreas

**Comment by geimist** [comment]
Hallo Andreas,
dann solltest du [den Wert](https://github.com/geimist/Update_Blocklist/blob/master/update_blocklist.sh#L28) `DELETE_IP_AFTER` entsprechend setzen. Standard ist hier 7 Tage. Das reicht meiner Meinung auch völlig zu, da in der Regel die IPs der Angreifer nach kurzer Zeit verbrannt sind, sobald sie in den ganzen Firewalls eingepflegt sind.
Wahrscheinlich greift der Parameter erst für neue IPs (das habe ich jetzt nicht gecheckt). Dann halt die alten IPs manuell löschen.

Gruß Stephan

**Comment by restaurierung** [comment]
Hallo Stephan

Danke dir für die rasche Rückmeldung. ich habe den Wert tatsächlich geändert und wohl damit zu hoch angesetzt. Ich werde mal mit dem Wert 7 Tage das Script ausführen lassen und das Ergebnis im Auge behalten.

Herzlichen Dank nochmal und lieben Gruss aus Zürich
Andreas
